// Generated by CoffeeScript 1.9.3
(function() {
  var brown, data;

  brown = require('./../index.coffee').parse;

  data = {
    master: {
      html: {
        head: '',
        body: {
          'div#main': '{{content()}}'
        }
      }
    },
    page: {
      'ul#menu': {
        div: "{{foo}}"
      }
    },
    data: {
      foo: "hello world"
    },
    content: function() {
      return brown(this.page, this.data);
    }
  };

  console.log(brown(data.master, data));

}).call(this);
