// Generated by CoffeeScript 1.10.0
(function() {
  var brown;

  brown = require('./../.');

  brown.micromustache["eval"] = function(arg) {
    var ref, v;
    console.log(arg);
    console.dir(this);
    v = eval("this." + arg);
    return (ref = v !== null) != null ? ref : {
      v: ''
    };
  };

  console.log(brown.render("{{eval:foo.bar}}", {
    foo: {
      bar: "flop"
    }
  }));

}).call(this);
