// Generated by CoffeeScript 1.10.0
(function() {
  var brown, data, str;

  brown = require('../index.coffee');

  console.log(brown.render("hello {{foo}}", {
    flop: {
      flap: 123
    },
    foo: "world"
  }));

  brown.encode = function(key) {
    var html;
    html = this[key] || '';
    return String(html).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/'/g, '&#39;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  };

  data = {
    href: "/",
    label: "my \"label\"",
    flop: {
      flap: 123
    },
    one: {
      two: function(arg) {
        return "foooooo " + arg;
      }
    }
  };

  str = '<a href="{{href}}" onclick="{{encode:label}}">{{flop.flap}} {{one.two:barrrrr}}</a>';

  console.log(brown.render(str, data));

}).call(this);
