// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = (function() {
    var k, merge, v;
    merge = this.merge = function(source, obj, clone) {
      var prop, v;
      if (source === null || (source == null)) {
        return source;
      }
      for (prop in obj) {
        v = obj[prop];
        if (source[prop] !== null && typeof source[prop] === 'object' && typeof obj[prop] === 'object') {
          this.merge(source[prop], obj[prop]);
        } else {
          if (clone) {
            source[prop] = this.clone;
          } else {
            source[prop] = obj[prop];
          }
        }
      }
      return source;
    };
    this.micromustache = require('micromustache');
    this.micromustache._render = this.micromustache.render;
    this.micromustache.render = (function(str, data) {
      return this._render(str, merge(data, this));
    }).bind(this.micromustache);
    this.render = function(input, data) {
      return this.micromustache.render(input, data);
    };
    for (k in this) {
      v = this[k];
      if (typeof v === 'function') {
        this[k] = v.bind(this);
      }
    }
    return this;
  }).apply({});

}).call(this);
